# Designed for ESP32-S3-Touch-LCD-7
esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 8MB
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: y
      CONFIG_ESP32S3_DATA_CACHE_64KB: y
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y
      CONFIG_ESPTOOLPY_FLASHSIZE_8MB: y

# Esphome
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  area: ${room}
  platformio_options:
    build_flags: "-DBOARD_HAS_PSRAM"
    board_build.esp-idf.memory_type: qio_opi
    board_build.flash_mode: dio
    board_upload.maximum_ram_size: 524288
    board_build.flash_size: 8MB

# Video memory
psram:
  mode: octal
  speed: 80MHz



# Over the Air Updates
ota:
- platform: esphome

# Enable Home Assistant API
api:

# Enable logging
logger:
  level: DEBUG
  hardware_uart: UART0

external_components:
  - source: github://pr#7427
    components: [lvgl, font]

  # CH422G I/O Expander
  # https://github.com/esphome/esphome/pull/7356
  - source: github://pr#7356
    components: [ch422g]

  # rpi_dpi_rgb
  # https://github.com/esphome/esphome/pull/7383
  - source: github://pr#7383
    components: [rpi_dpi_rgb]

i2c:
  - id: bus_a
    sda: GPIO8
    scl: GPIO9
    scan: true

ch422g:
  - id: io_ex
    address: 0x24


# Backlight
switch:
  - platform: gpio
    name: "Backlight Toggle"
    pin: 
      ch422g: io_ex
      number: 2
      allow_other_uses: true
# CH422G saves the last state internally, but gpio switch sets state as off except when using RESTORE_ modes
    restore_mode: ALWAYS_ON


touchscreen:
  platform: gt911
  address: 0x5D
  id: my_touchscreen
  update_interval: 16ms
  interrupt_pin: 4
  on_touch:
    - lambda: |-
          ESP_LOGI("cal", "x=%d, y=%d, x_raw=%d, y_raw=%0d",
              touch.x,
              touch.y,
              touch.x_raw,
              touch.y_raw
              );

display:
  - platform: rpi_dpi_rgb
    id: my_display
    #rotation: 90
    auto_clear_enabled: false
    update_interval: never
    color_order: RGB
    pclk_frequency: 14MHz
    dimensions:
      width: 800
      height: 480
    de_pin:
      number: 5
    reset_pin:
      ch422g: io_ex
      number: 3
    enable_pin:
      ch422g: io_ex
      number: 2
      allow_other_uses: true
    hsync_pin:
      number: 46
      ignore_strapping_warning: true
    vsync_pin:
      number: 3
      ignore_strapping_warning: true
    pclk_pin: 7
    pclk_inverted: false
    hsync_back_porch: 10
    hsync_front_porch: 20
    hsync_pulse_width: 10
    vsync_back_porch: 10
    vsync_front_porch: 10
    vsync_pulse_width: 10
    data_pins:
      red:
        - 1 # R3
        - 2 # R4
        - 42 # R5
        - 41 # R6
        - 40 # R7
      green:
        - 39 # G2
        - 0 # G3
        - 45 # G4
        - 48 # G5
        - 47 # G6
        - 21 # G7
      blue:
        - 14 # B3
        - 38 # B4
        - 18 # B5
        - 17 # B6
        - 10 # B7

# Screen Setup
lvgl: