binary_sensor:
  - platform: homeassistant
    id: office_feature_lights
    entity_id: light.office_feature_lights
    on_turn_on:
      - lvgl.widget.update:
          id: light_switch
          state:
            checked: true
    on_turn_off:
      - lvgl.widget.update:
          id: light_switch
          state:
            checked: false
