sensor:
  - platform: homeassistant
    id: light_brightness
    entity_id: light.office_lamp_light
    attribute: brightness
    on_value:
      - lvgl.slider.update:
          id: dimmer_slider
          value: !lambda return x;
