substitutions:
  icon_font: icon_font
  text_font: roboto17_font
  button_on_color: "Dark_Orange"
  icon_on_color: "Yellow"
  icon_off_color: "White"
  button_text_color: "White"
  button_height_single: 102px
  button_height_double: 220px
  button_width: 149px
  padding: 8px
  radius: 12px

lvgl:
  style_definitions:
    - id: webhook
      bg_color: "Night_Grey"

    - id: control
      bg_color: "Very_Dark_Gray"
      
  theme:
    button:
      text_font: $text_font
      scroll_on_focus: false
      radius: $radius
      width: $button_width
      height: $button_height_single
      pad_all: $padding
      shadow_width: 0
      text_color: $button_text_color
      checked:
        bg_color: $button_on_color
        text_color: $button_text_color
