# http://materialdesignicons.com/cdn/7.4.47/

font:
  - file: 'https://github.com/Templarian/MaterialDesign-Webfont/raw/v7.4.47/fonts/materialdesignicons-webfont.ttf'
    id: light40
    #size: 40
    size: 32
    bpp: 4
    glyphs: [
      "\U000F0335",  # mdi-lightbulb
    ]       


substitutions:
  lightbulb:         "\U000F0335"
  printer:           "\U000F042B"
