substitutions:
  icon_font: light40
  text_font: roboto24  
  button_on_color: "Dark_Orange"
  icon_on_color: "Yellow"
  button_off_color: "Very_Dark_Gray"
  icon_off_color: "White"
  button_text_color: "White"
  button_height_single: '109px'
  button_height_double: '228px'
  button_width: '150px' 

lvgl:
  theme:
    button:
      text_font: $text_font
      scroll_on_focus: true
      radius: 12px
      width: $button_width
      height: $button_height_single
      pad_all: 8px
      shadow_width: 0 # This is required even though the default is suposed to be 0
      bg_color: Very_Dark_Gray
      text_color: Gray
      checked:
        bg_color: $button_on_color
        text_color: Gray
