substitutions:
  icon_font: light40
  text_font: roboto24  
  button_on_color: "Dark_Orange"
  icon_on_color: "Yellow"
  button_off_color: "Very_Dark_Gray"
  icon_off_color: "White"
  button_text_color: "White"
  button_hight_single: '109px'
  button_hight_double: '228px'
  button_width: '150px'

lvgl:
  theme:
    button:
      scroll_on_focus: true
      radius: 12
      width: $button_width
      height: $button_hight_single
      pad_left: 10px
      pad_top: 10px
      pad_bottom: 10px
      pad_right: 10px
      shadow_width: 0
      bg_color: $button_off_color
      text_color: $button_text_color
      checked:
        bg_color: $button_on_color
        text_color: $button_text_color
