substitutions:
  icon_font: light40
  text_font: roboto24  
  button_on_color: "Dark_Orange"
  icon_on_color: "Yellow"
  button_off_color: "Very_Dark_Gray"
  icon_off_color: "White"
  button_text_color: "White"
  button_height_single: '96px'
  button_width: '110px'

lvgl:
  style_definitions:
    - id: no_checked_color
      bg_color: 0xCC5E14
      text_color: 0xB6B6B6
  theme:
    button:
      scroll_on_focus: true
      radius: 5
      width: $button_width
      height: $button_height
      pad_left: 10px
      pad_top: 10px
      pad_bottom: 10px
      pad_right: 10px
      shadow_width: 0
      bg_color: $button_off_color
      text_color: $button_text_color
      checked:
        bg_color: $button_on_color
        text_color: $button_text_color
