# Panel Backlight
switch:
  - platform: gpio
    id: backlight
    pin: 
      ch422g: io_ex
      number: 2
    restore_mode: ALWAYS_ON
    internal: true

# Presence Sensor
binary_sensor:
  - platform: homeassistant
    id: presence
    entity_id: binary_sensor.office_presence_presence
    on_press:
      - lvgl.resume:
      - delay: 5ms
      - switch.turn_on: backlight
      - logger.log: "Screensaver is turned off"

    on_release:
      - switch.turn_off: backlight
      - lvgl.pause:
          show_snow: true
      - logger.log: "Screensaver is turned on"

# Stops screen saver
touchscreen:
  on_touch:
    then:
      - logger.log: "Screen is active"
      - lvgl.resume:
      - switch.turn_on: backlight
