# Panel Backlight
output:
  - platform: gpio
    pin: 
      ch422g: io_ex
      number: 2
    id: backlight_output

light:
  - platform: binary
    id: display_backlight
    output: backlight_output
    id: backlight_light
    on_turn_on:
      then:
        - delay: 100ms  # Delay of 100 milliseconds
        - output.turn_on: backlight_output

    
# Presence Sensor
binary_sensor:
  - platform: homeassistant
    id: backlight_presence
    entity_id: binary_sensor.office_presence_presence
    on_press:
      - logger.log: "Screensaver is turned off"
      - light.turn_on: display_backlight
      - lvgl.resume:
    on_release:
      - logger.log: "Screensaver is turned on"
      - light.turn_off: display_backlight
      - lvgl.pause:
          show_snow: true

# Stops screen saver
touchscreen:
  on_touch:
    then:
      - logger.log: "Screen is active"
      - lvgl.resume:
      - light.turn_on: display_backlight
