# Panel Backlight
switch:
  - platform: gpio
    name: Display Backlight
    id: display_backlight
    pin: 
      ch422g: io_ex
      number: 2
    restore_mode: ALWAYS_ON
    #internal: true

# Presence Sensor
binary_sensor:
  - platform: homeassistant
    id: backlight_presence
    entity_id: binary_sensor.office_presence_presence
    on_press:
      - logger.log: "Screensaver is turned off"
      - switch.turn_on: display_backlight
      - lvgl.resume:
    on_release:
      - logger.log: "Screensaver is turned on"
      - switch.turn_off: display_backlight
      - lvgl.pause:
          show_snow: true

# Stops screen saver
touchscreen:
  on_touch:
    then:
      - logger.log: "Screen is active"
      - lvgl.resume:
      - switch.turn_on: display_backlight
