# Panel Backlight
switch:
  - platform: gpio
    id: display_backlight_switch
    pin: 
      ch422g: io_ex
      number: 2
      allow_other_uses: true
    restore_mode: ALWAYS_ON
    internal: true

light:
  - platform: monochromatic
    output: backlight_pwm
    id: display_backlight
    internal: true
    name: "Display Backlight"

binary_sensor:
  - platform: homeassistant
    id: office_presence
    entity_id: binary_sensor.office_presence_presence
    on_press:
      - light.turn_on:
          id: display_backlight
          brightness: 100%  # Full brightness
          transition_length: 1s    # Fade up over 1 second
    on_release:
      - light.turn_off:
          id: display_backlight
          transition_length: 1s    # Fade down over 1 second
