# Designed for ESP32-S3-Touch-LCD-7
esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  area: ${room}
  platformio_options:
    # build_unflags: -Werror=all
    board_build.flash_mode: dio

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    platform_version: 6.8.1
    version: 5.3.0
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y
  flash_size: 16MB
  
psram:
  mode: octal
  speed: 80MHz

external_components:
  # CH422G I/O Expander
  # https://github.com/esphome/esphome/pull/7356
  - source: github://pr#7356
    components: [ch422g]
  
api:

logger:
  hardware_uart: USB_SERIAL_JTAG

ota:
  platform: esphome

ch422g:
  - id: io_ex
    address: 0x24

i2c:
  sda: 8
  scl: 9
  frequency: 400kHz
  scan: false
  id: bus_a

touchscreen:
  - platform: gt911
    i2c_id: bus_a
    address: 0x5D
    id: device_touchscreen

display:
  - platform: rpi_dpi_rgb
    id: device_display
    update_interval: never
    auto_clear_enabled: false
    color_order: RGB
    pclk_frequency: 16MHz
    dimensions:
      width: 800
      height: 480
    reset_pin:
      ch422g: io_ex
      number: 3
    de_pin:
      number: 5
    hsync_pin:
      number: 46
      ignore_strapping_warning: true
    vsync_pin:
      number: 3
      ignore_strapping_warning: true
    # enable_pin:
      # # allow_other_uses: true
      # ch422g: io_ex
      # number: 2
    pclk_pin: 7
    pclk_inverted: true
    hsync_back_porch: 8
    hsync_front_porch: 8
    hsync_pulse_width: 4
    vsync_back_porch: 16
    vsync_front_porch: 16
    vsync_pulse_width: 4
    data_pins:
      red:
        - 1         #r3.
        - 2         #r4.
        - 42        #r5
        - 41        #r6
        - 40        #r7
      blue:
        - 14        #b3
        - 38        #b4
        - 18        #b5
        - 17        #b6
        - 10        #b7
      green:
        - 39        #g2
        - 0         #g3.
        - 45        #g4
        - 48        #g5
        - 47        #g6
        - 21        #g7

output:
  - platform: ledc
    pin: EXIO2
    id: backlight_output
    zero_means_zero: true
light:
  - platform: monochromatic
    id: backlight
    name: Back Light
    entity_category: config
    output: backlight_output
    restore_mode: ALWAYS_ON
