substitutions:
  icon_font: light40
  text_font: roboto24
  screen_height: '480px'
  screen_width: '480px'
  button_on_color: "Burnt_Sienna"
  button_off_color: "Very_Dark_Gray"  
  icon_on_color: "Yellow"
  icon_off_color: "Gray"
  label_on_color: "White"  
  label_off_color: "Gray"
  button_text_color: "White"
  button_height_single: '109px'
  button_height_double: '228px'
  button_width: '150px'

lvgl:
  pages:
    - id: main_page
      layout: 
        type: flex
        flex_flow: column_wrap
      width: 100%
      bg_color: Black
      bg_opa: cover
      pad_all: 5
      widgets:

      # Button 1
        - button: 
            height: $button_height_single
            checkable: true
            id: office_lamp_light_button
            widgets:
              - label:
                  text_font: $icon_font
                  align: top_left
                  id: office_lamp_light_icon                  
                  text: $lightbulb
              - label:
                  align: bottom_left
                  id: office_lamp_light_label
                  text: "Office Light"
            on_click:
                - homeassistant.service:
                    service: light.toggle
                    data:
                      entity_id: light.office_lamp_light
