substitutions:
  button_1_name: "Local Light"
  button_1_id: local_light
  button_1_icon: $lightbulb
  button_1_device: light.office_lamp_light

  icon_font: light40
  text_font: roboto24
  screen_height: '480px'
  screen_width: '480px'
  button_on_color: "Burnt_Sienna"
  button_off_color: "Very_Dark_Gray"  
  icon_on_color: "Yellow"
  icon_off_color: "Gray"
  label_on_color: "White"  
  label_off_color: "Gray"
  button_text_color: "White"
  button_height_single: '109px'
  button_height_double: '228px'
  button_width: '150px'
  touchscreen_idle_timeout: "120s"
  touchscreen_daytime_brightness: "100%"
  touchscreen_nighttime_brightness: "50%"
  # Screen goes to sleep at Mightnight
  screen_sleep_hour: '0'
  screen_sleep_minute: '0'
  # Screen wakes up at 5:30am
  screen_wake_hour: '5'
  screen_wake_minute: '30'

  # Icons
  lightbulb:         "\U000F0335"
  ceiling_light:     "\U000F0769"
  lamp:              "\U000F06B5"
  floor_lamp:        "\U000F08DD"
  string_lights:     "\U000F12BA"
  track_light:       "\U000F0914"
  bulkhead_light:    "\U000F1A2F" 
  led_strip:         "\U000F07D6" 
  coach_lamp:        "\U000F1020"
  ceiling_fan_light: "\U000F1798"

lvgl:
  pages:
    - id: main_page
      layout: 
        type: flex
        flex_flow: column_wrap
      width: 100%
      bg_color: Black
      bg_opa: cover
      pad_all: 5
      widgets:
      - button: 
        height: $button_height_single
        checkable: true
        id: lv_button_1
        widgets:
          - label:
              text_font: $icon_font
              align: top_left
              id: lv_button_1_icon                  
              text: $button_1_icon
          - label:
              align: bottom_left
              id: lv_button_1_label
              text: $button_1_name
        on_click:
            - homeassistant.service:
                service: switch.toggle
                data:
                  entity_id: $button_1_device
