binary_sensor:

  # Office Evening Scene
  - platform: homeassistant
    id: office_scene_evening
    entity_id: binary_sensor.office_scene_evening
    publish_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: office_scene_evening_button
          state:
            checked: !lambda return x;

  # Office Calls Scene
  - platform: homeassistant
    id: office_scene_desk_call
    entity_id: binary_sensor.office_scene_desk_call
    publish_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: office_scene_calls_button
          state:
            checked: !lambda return x;

  # Office Features Scene
  - platform: homeassistant
    id: office_scene_features
    entity_id: binary_sensor.office_scene_features
    publish_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: office_scene_features_button
          state:
            checked: !lambda return x;

  # Office Storage Light
  - platform: homeassistant
    id: office_storage
    entity_id: light.office_storage
    publish_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: office_storage_light_button
          state:
            checked: !lambda return x;

  # 3d Printer
  - platform: homeassistant
    id: office_3d_printer_power
    entity_id: switch.office_3d_printer_power
    publish_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: printer_power_button
          state:
            checked: !lambda return x;

  # 3d Printer Lights
  - platform: homeassistant
    id: office_3d_printer_lights
    entity_id: switch.office_3d_printer_lights
    publish_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: printer_lights_button
          state:
            checked: !lambda return x;

  # Lenovo Server
  - platform: homeassistant
    id: office_lenovo_power_switch
    entity_id: switch.office_lenovo_power_switch
    publish_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: lenovo_power_button
          state:
            checked: !lambda return x;

  # Office Blind
  - platform: homeassistant
    id: office_blind
    entity_id: binary_sensor.office_blind_state
    publish_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: office_blind_button
          state:
            checked: !lambda return x;


#  # Office Aircon
#  - platform: homeassistant
#    id: office_air_conditioner
#    entity_id: binary_sensor.office_air_conditioner
#    publish_initial_state: true
#    on_state:
#      then:
#        lvgl.widget.update:
#          id: office_aircon_button
#          state:
#            checked: !lambda return x;

  - platform: homeassistant
    id: office_air_conditioner_switch
    entity_id: switch.office_air_conditioner_switch
    on_state:
      then:
        - if:
            condition:
              binary_sensor.is_on: office_air_conditioner_switch
            then:
              - homeassistant.service:
                  service: climate.set_hvac_mode
                  data:
                    entity_id: climate.office_air_conditioner
                    hvac_mode: "auto"
            else:
              - homeassistant.service:
                  service: climate.set_hvac_mode
                  data:
                    entity_id: climate.office_air_conditioner
                    hvac_mode: "off"

switch:
  - platform: lvgl
    id: office_air_conditioner_switch
    widget: office_aircon_button
#    turn_on_action:
#      - homeassistant.service:
#          service: climate.set_hvac_mode
#          data:
#            entity_id: climate.office_air_conditioner
#            hvac_mode: "auto"
#    turn_off_action:
#      - homeassistant.service:
#          service: climate.set_hvac_mode
#          data:
#            entity_id: climate.office_air_conditioner
#            hvac_mode: "off"

script:
  - id: aircon
    then:      
      - if: 
          condition:
            light.is_off: backlight
          then: 
            - lvgl.resume:
            - delay: 100ms
            - light.turn_on: backlight
            - delay: 180s
            - light.turn_off: backlight
            - lvgl.page.show: main_page
            - lvgl.pause:
                show_snow: true
