binary_sensor:

  # Office Evening Scene
  - platform: homeassistant
    id: office_scene_evening_sensor
    entity_id: binary_sensor.office_scene_evening
    publish_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: office_scene_evening_button
          state:
            checked: !lambda return x;

  # Office Calls Scene
  - platform: homeassistant
    id: office_scene_calls_sensor
    entity_id: binary_sensor.office_scene_desk_call
    publish_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: office_scene_calls_button
          state:
            checked: !lambda return x;

  # Office Features Scene
  - platform: homeassistant
    id: office_scene_features_sensor
    entity_id: binary_sensor.office_scene_features
    publish_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: office_scene_features_button
          state:
            checked: !lambda return x;

  # Office Storage Light
  - platform: homeassistant
    id: office_storage_light_sensor
    entity_id: light.office_storage
    publish_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: office_storage_light_button
          state:
            checked: !lambda return x;

  # 3d Printer
  - platform: homeassistant
    id: homeassistant_printer_power_sensor
    entity_id: switch.office_3d_printer_power
    publish_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: printer_power_button
          state:
            checked: !lambda return x;

  # 3d Printer Lights
  - platform: homeassistant
    id: printer_lights_sensor
    entity_id: switch.office_3d_printer_lights
    publish_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: printer_lights_button
          state:
            checked: !lambda return x;

  # Lenovo Server
  - platform: homeassistant
    id: homeassistant_lenovo_power_sensor
    entity_id: switch.office_lenovo_power_switch
    publish_initial_state: true
    on_state:
      then:
        lvgl.widget.update:
          id: lenovo_power_button
          state:
            checked: !lambda return x;
